// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHyweGhVtjnpjRLdmAoV1Q7vYPPayk54',
    appId: '1:631515397076:web:b78cfe81d9820115a0f441',
    messagingSenderId: '631515397076',
    projectId: 'final-projesi-c84d5',
    authDomain: 'final-projesi-c84d5.firebaseapp.com',
    storageBucket: 'final-projesi-c84d5.appspot.com',
    measurementId: 'G-04JZ3SXH0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4a34sWXVFH_0SiBDMjGwL64YeFdrcCjE',
    appId: '1:631515397076:android:a4246470126a935ca0f441',
    messagingSenderId: '631515397076',
    projectId: 'final-projesi-c84d5',
    storageBucket: 'final-projesi-c84d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6zvdaIxSPGs59hIcf5XEZteMR7jEWfo',
    appId: '1:631515397076:ios:a87068137bff1512a0f441',
    messagingSenderId: '631515397076',
    projectId: 'final-projesi-c84d5',
    storageBucket: 'final-projesi-c84d5.appspot.com',
    iosBundleId: 'com.example.finalprojesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6zvdaIxSPGs59hIcf5XEZteMR7jEWfo',
    appId: '1:631515397076:ios:987c3892c53fff7aa0f441',
    messagingSenderId: '631515397076',
    projectId: 'final-projesi-c84d5',
    storageBucket: 'final-projesi-c84d5.appspot.com',
    iosBundleId: 'com.example.finalprojesi.RunnerTests',
  );
}
